---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-auth
  namespace: devlake
type: Opaque
data:
  # Contraseña root (Base64) -> MiPasswordSeguro123!
  mariadb-root-password: TWlQYXNzd29yZFNlZ3VybzEyMyE=
  # Contraseña usuario devlake (Base64) -> DevLakePassword4567
  mariadb-password: RGV2TGFrZVBhc3N3b3JkNDU2Nw==
  # Nombre de la base de datos (Base64) -> lake
  mariadb-database: bGFrZQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: devlake-mariadb-auth
  namespace: devlake
type: Opaque
data:
  MYSQL_USER: ZGV2bGFrZQ==                          
  MYSQL_PASSWORD: RGV2TGFrZVBhc3N3b3JkNDU2Nw==      
  MYSQL_DATABASE: bGFrZQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: encryption-secret
  namespace: devlake
type: Opaque
data:
  ENCRYPTION_SECRET: UTd2THg5WXBLM21SOHRXY04yc0RmR2hKa0x6WDRiUGE=
---
apiVersion: v1
kind: Secret
metadata:
  name: devlake-db-secret
  namespace: devlake
type: Opaque
data:
  MYSQL_USERNAME: ZGV2bGFrZQ==                    # devlake
  MYSQL_PASSWORD: RGV2TGFrZVBhc3N3b3JkNDU2Nw==    # DevLakePassword4567
  MYSQL_DATABASE: bGFrZQ==                        # lake
  DB_URL: bXlzcWw6Ly9kZXZsYWtlOkRldkxha2VQYXNzd29yZDQ1NjdAZGV2bGFrZS1tYXJpYWRiLmRldmxha2Uuc3ZjLmNsdXN0ZXIubG9jYWw6MzMwNi9sYWtlP2NoYXJzZXQ9dXRmOG1iNCZwYXJzZVRpbWU9VHJ1ZSZsb2M9VVRD # mysql://devlake:DevLakePassword4567@devlake-mariadb.devlake.svc.cluster.local:3306/lake?charset=utf8mb4&parseTime=True&loc=UTC
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: devlake-db-config
  namespace: devlake
data:
  MYSQL_HOST: "devlake-mariadb.devlake.svc.cluster.local"
  MYSQL_PORT: "3306"
  TZ: "UTC"
---
apiVersion: v1
kind: Secret
metadata:
  name: devlake-ui-auth
  namespace: devlake
type: Opaque
data:
  ADMIN_USER: YWRtaW4=
  ADMIN_PASS: VjY4M0tJdjQyZ244