apiVersion: v1
kind: Service
metadata:
  name: vault-unseal-frontend
  namespace: vault
  labels:
    app: vault-unseal-frontend
spec:
  selector:
    app: vault-unseal-frontend
  ports:
  - name: frontend
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP