/*
API Off-Chain del Banco Central

Testing DefaultAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_DefaultAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DefaultAPIService GetAssetPrice", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var asset string

		resp, httpRes, err := apiClient.DefaultAPI.GetAssetPrice(context.Background(), asset).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetContractMetadata", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var contractId string

		resp, httpRes, err := apiClient.DefaultAPI.GetContractMetadata(context.Background(), contractId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetTransactionDetails", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var txHash string

		resp, httpRes, err := apiClient.DefaultAPI.GetTransactionDetails(context.Background(), txHash).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
