apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cloudnative-pg-operator.yaml
  - vault-db-secret.yaml
  - postgres-cluster.yaml
  - vault-override-values-configmap.yaml
  - helmrelease-vault.yaml
  #- ./vault-init/vault-init-configmap.yaml
  #- ./vault-init/vault-init-rbac.yaml
  #- ./vault-init/vault-init-deployment.yaml
  #- ./vault-init/vault-init-service.yaml
  - ./vault-init/vault-init-script-configmap.yaml
  - ./vault-init/vault-init-rbac.yaml
  - ./vault-init/vault-init-job-improved.yaml