apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vault-postgres
  namespace: vault
spec:
  instances: 1

  imageName: ghcr.io/cloudnative-pg/postgresql:15

  storage:
    size: 10Gi

  bootstrap:
    initdb:
      database: vault
      owner: vault
      secret:
        name: vault-db-secret

  postgresql:
    parameters:
      max_connections: "100"

  monitoring:
    enablePodMonitor: true