apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-override-values
  namespace: vault
data:
  override-values.yaml: |
    ui:
      enabled: true
      serviceType: LoadBalancer
      serviceNodePort: null
      externalPort: 8200