apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: devops-psql-auth
  namespace: external-secrets
spec:
  refreshTime: "1m"
  namespaceSelector:
    matchLabels:
      devops-psql-auth: psql-auth
  externalSecretSpec:
    secretStoreRef:
      name: cluster-external-store-vault
      kind: ClusterSecretStore
    target:
      name: psql-auth
    data:
    - secretKey: postgresql-username
      remoteRef:
        key: data/cluster-production
        property: postgresql-username

    - secretKey: postgresql-password
      remoteRef:
        key: data/cluster-production
        property: postgresql-password
    
    - secretKey: url-artifactory
      remoteRef:
        key: data/cluster-production
        property: url-artifactory