apiVersion: v1
kind: Service
metadata:
  name: vault-unseal-manager
  namespace: vault
spec:
  selector:
    app: vault-unseal-manager
  ports:
  - name: backend
    port: 8000
    targetPort: 8000
  - name: frontend
    port: 8080
    targetPort: 80
  type: ClusterIP