apiVersion: v1
data:
  password: QWRtaW4xMjM=
  username: ZGV2bGFrZQ== # ## admin/YWRtaW4=
kind: Secret
metadata:
  name: postgres-devlake-user
  namespace: devlake-cloudnative-pg
type: kubernetes.io/basic-auth
---
apiVersion: v1
data:
  password: QWRtaW4xMjM=
  username: cG9zdGdyZXM=
kind: Secret
metadata:
  name: postgres-devlake-superuser
  namespace: devlake-cloudnative-pg
type: kubernetes.io/basic-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: devlake-mysql-auth
  namespace: devlake-cloudnative-pg
type: Opaque
data:
  mysql-root-password: dHUtcGFzc3dvcmQtcm9vdA== 
  mysql-password: dHUtcGFzc3dvcmQtZGV2bGFrZQ== 
  password: dHUtcGFzc3dvcmQtZGV2bGFrZQ== 
---
apiVersion: v1
kind: Secret
metadata:
  name: encryption-secret
  namespace: devlake-cloudnative-pg
type: Opaque
data:
  ENCODE_KEY: dGhpc2lzYWZha2VrZXlvbmx5Zm9yZGVtb3B1cnBvc2VzCg==
---
apiVersion: v1
kind: Secret
metadata:
  name: devlake-db-url
  namespace: devlake-cloudnative-pg
type: Opaque
stringData:
  # Apunta al pooler RW de CloudNativePG
  # Formato: postgres://<user>:<password>@<host>:<port>/<database>?sslmode=disable
  DB_URL: "postgres://devlake:Admin123@postgres-devlake-pool-rw.devlake-cloudnative-pg.svc.cluster.local:5432/lake?sslmode=disable"