/* tslint:disable */
/* eslint-disable */
/**
 * API Off-Chain del Banco Central
 * API para exponer datos complementarios de la blockchain a sistemas internos y externos de forma estandarizada.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface ContractMetadata {
    'name'?: string;
    'version'?: string;
    'parameters'?: Array<ContractMetadataParametersInner>;
}
export interface ContractMetadataParametersInner {
    'name'?: string;
    'type'?: string;
    'value'?: string;
}
export interface PriceReference {
    'asset'?: string;
    'price'?: number;
}
export interface TransactionDetails {
    'txHash'?: string;
    'details'?: TransactionDetailsDetails;
}
export interface TransactionDetailsDetails {
    'businessData'?: string;
    'multiSignature'?: boolean;
}

/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Obtener precio de un activo
         * @param {string} asset Nombre del activo
         * @param {string} [fromDate] Fecha de inicio para filtrar resultados
         * @param {string} [toDate] Fecha de fin para filtrar resultados
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAssetPrice: async (asset: string, fromDate?: string, toDate?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'asset' is not null or undefined
            assertParamExists('getAssetPrice', 'asset', asset)
            const localVarPath = `/offchain/prices/{asset}`
                .replace(`{${"asset"}}`, encodeURIComponent(String(asset)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            if (fromDate !== undefined) {
                localVarQueryParameter['fromDate'] = (fromDate as any instanceof Date) ?
                    (fromDate as any).toISOString().substring(0,10) :
                    fromDate;
            }

            if (toDate !== undefined) {
                localVarQueryParameter['toDate'] = (toDate as any instanceof Date) ?
                    (toDate as any).toISOString().substring(0,10) :
                    toDate;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Obtener metadata de un contrato inteligente
         * @param {string} contractId ID del contrato inteligente
         * @param {string} [fromDate] Fecha de inicio para filtrar resultados
         * @param {string} [toDate] Fecha de fin para filtrar resultados
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getContractMetadata: async (contractId: string, fromDate?: string, toDate?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'contractId' is not null or undefined
            assertParamExists('getContractMetadata', 'contractId', contractId)
            const localVarPath = `/offchain/contracts/{contractId}/metadata`
                .replace(`{${"contractId"}}`, encodeURIComponent(String(contractId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            if (fromDate !== undefined) {
                localVarQueryParameter['fromDate'] = (fromDate as any instanceof Date) ?
                    (fromDate as any).toISOString().substring(0,10) :
                    fromDate;
            }

            if (toDate !== undefined) {
                localVarQueryParameter['toDate'] = (toDate as any instanceof Date) ?
                    (toDate as any).toISOString().substring(0,10) :
                    toDate;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Obtener detalles de una transacción
         * @param {string} txHash Hash de la transacción
         * @param {string} [fromDate] Fecha de inicio para filtrar resultados
         * @param {string} [toDate] Fecha de fin para filtrar resultados
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTransactionDetails: async (txHash: string, fromDate?: string, toDate?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'txHash' is not null or undefined
            assertParamExists('getTransactionDetails', 'txHash', txHash)
            const localVarPath = `/offchain/transactions/{txHash}/details`
                .replace(`{${"txHash"}}`, encodeURIComponent(String(txHash)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            if (fromDate !== undefined) {
                localVarQueryParameter['fromDate'] = (fromDate as any instanceof Date) ?
                    (fromDate as any).toISOString().substring(0,10) :
                    fromDate;
            }

            if (toDate !== undefined) {
                localVarQueryParameter['toDate'] = (toDate as any instanceof Date) ?
                    (toDate as any).toISOString().substring(0,10) :
                    toDate;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Obtener precio de un activo
         * @param {string} asset Nombre del activo
         * @param {string} [fromDate] Fecha de inicio para filtrar resultados
         * @param {string} [toDate] Fecha de fin para filtrar resultados
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAssetPrice(asset: string, fromDate?: string, toDate?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PriceReference>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAssetPrice(asset, fromDate, toDate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getAssetPrice']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Obtener metadata de un contrato inteligente
         * @param {string} contractId ID del contrato inteligente
         * @param {string} [fromDate] Fecha de inicio para filtrar resultados
         * @param {string} [toDate] Fecha de fin para filtrar resultados
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getContractMetadata(contractId: string, fromDate?: string, toDate?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ContractMetadata>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getContractMetadata(contractId, fromDate, toDate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getContractMetadata']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Obtener detalles de una transacción
         * @param {string} txHash Hash de la transacción
         * @param {string} [fromDate] Fecha de inicio para filtrar resultados
         * @param {string} [toDate] Fecha de fin para filtrar resultados
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTransactionDetails(txHash: string, fromDate?: string, toDate?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TransactionDetails>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTransactionDetails(txHash, fromDate, toDate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getTransactionDetails']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Obtener precio de un activo
         * @param {string} asset Nombre del activo
         * @param {string} [fromDate] Fecha de inicio para filtrar resultados
         * @param {string} [toDate] Fecha de fin para filtrar resultados
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAssetPrice(asset: string, fromDate?: string, toDate?: string, options?: RawAxiosRequestConfig): AxiosPromise<PriceReference> {
            return localVarFp.getAssetPrice(asset, fromDate, toDate, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Obtener metadata de un contrato inteligente
         * @param {string} contractId ID del contrato inteligente
         * @param {string} [fromDate] Fecha de inicio para filtrar resultados
         * @param {string} [toDate] Fecha de fin para filtrar resultados
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getContractMetadata(contractId: string, fromDate?: string, toDate?: string, options?: RawAxiosRequestConfig): AxiosPromise<ContractMetadata> {
            return localVarFp.getContractMetadata(contractId, fromDate, toDate, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Obtener detalles de una transacción
         * @param {string} txHash Hash de la transacción
         * @param {string} [fromDate] Fecha de inicio para filtrar resultados
         * @param {string} [toDate] Fecha de fin para filtrar resultados
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTransactionDetails(txHash: string, fromDate?: string, toDate?: string, options?: RawAxiosRequestConfig): AxiosPromise<TransactionDetails> {
            return localVarFp.getTransactionDetails(txHash, fromDate, toDate, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Obtener precio de un activo
     * @param {string} asset Nombre del activo
     * @param {string} [fromDate] Fecha de inicio para filtrar resultados
     * @param {string} [toDate] Fecha de fin para filtrar resultados
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAssetPrice(asset: string, fromDate?: string, toDate?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getAssetPrice(asset, fromDate, toDate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Obtener metadata de un contrato inteligente
     * @param {string} contractId ID del contrato inteligente
     * @param {string} [fromDate] Fecha de inicio para filtrar resultados
     * @param {string} [toDate] Fecha de fin para filtrar resultados
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getContractMetadata(contractId: string, fromDate?: string, toDate?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getContractMetadata(contractId, fromDate, toDate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Obtener detalles de una transacción
     * @param {string} txHash Hash de la transacción
     * @param {string} [fromDate] Fecha de inicio para filtrar resultados
     * @param {string} [toDate] Fecha de fin para filtrar resultados
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getTransactionDetails(txHash: string, fromDate?: string, toDate?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getTransactionDetails(txHash, fromDate, toDate, options).then((request) => request(this.axios, this.basePath));
    }
}



