/* tslint:disable */
/* eslint-disable */
/**
 * API Off-Chain del Banco Central
 * API para exponer datos complementarios de la blockchain a sistemas internos y externos de forma estandarizada.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

