apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rbac-manager
resources:
  - namespace.yaml
  - env-configmap.yaml
  - pvc.yaml
  - deployment-backend.yaml
  - deployment-frontend.yaml
  - service-backend.yaml
  - service-frontend.yaml
  - service-account.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  #- ingress.yaml