/*
API Off-Chain del Banco Central

API para exponer datos complementarios de la blockchain a sistemas internos y externos de forma estandarizada.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ContractMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContractMetadata{}

// ContractMetadata struct for ContractMetadata
type ContractMetadata struct {
	Name *string `json:"name,omitempty"`
	Version *string `json:"version,omitempty"`
	Parameters []ContractMetadataParametersInner `json:"parameters,omitempty"`
}

// NewContractMetadata instantiates a new ContractMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContractMetadata() *ContractMetadata {
	this := ContractMetadata{}
	return &this
}

// NewContractMetadataWithDefaults instantiates a new ContractMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContractMetadataWithDefaults() *ContractMetadata {
	this := ContractMetadata{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ContractMetadata) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContractMetadata) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ContractMetadata) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ContractMetadata) SetName(v string) {
	o.Name = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *ContractMetadata) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContractMetadata) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *ContractMetadata) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *ContractMetadata) SetVersion(v string) {
	o.Version = &v
}

// GetParameters returns the Parameters field value if set, zero value otherwise.
func (o *ContractMetadata) GetParameters() []ContractMetadataParametersInner {
	if o == nil || IsNil(o.Parameters) {
		var ret []ContractMetadataParametersInner
		return ret
	}
	return o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContractMetadata) GetParametersOk() ([]ContractMetadataParametersInner, bool) {
	if o == nil || IsNil(o.Parameters) {
		return nil, false
	}
	return o.Parameters, true
}

// HasParameters returns a boolean if a field has been set.
func (o *ContractMetadata) HasParameters() bool {
	if o != nil && !IsNil(o.Parameters) {
		return true
	}

	return false
}

// SetParameters gets a reference to the given []ContractMetadataParametersInner and assigns it to the Parameters field.
func (o *ContractMetadata) SetParameters(v []ContractMetadataParametersInner) {
	o.Parameters = v
}

func (o ContractMetadata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContractMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.Parameters) {
		toSerialize["parameters"] = o.Parameters
	}
	return toSerialize, nil
}

type NullableContractMetadata struct {
	value *ContractMetadata
	isSet bool
}

func (v NullableContractMetadata) Get() *ContractMetadata {
	return v.value
}

func (v *NullableContractMetadata) Set(val *ContractMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableContractMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableContractMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContractMetadata(val *ContractMetadata) *NullableContractMetadata {
	return &NullableContractMetadata{value: val, isSet: true}
}

func (v NullableContractMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContractMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


