/*
API Off-Chain del Banco Central

API para exponer datos complementarios de la blockchain a sistemas internos y externos de forma estandarizada.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TransactionDetailsDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransactionDetailsDetails{}

// TransactionDetailsDetails struct for TransactionDetailsDetails
type TransactionDetailsDetails struct {
	BusinessData *string `json:"businessData,omitempty"`
	MultiSignature *bool `json:"multiSignature,omitempty"`
}

// NewTransactionDetailsDetails instantiates a new TransactionDetailsDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionDetailsDetails() *TransactionDetailsDetails {
	this := TransactionDetailsDetails{}
	return &this
}

// NewTransactionDetailsDetailsWithDefaults instantiates a new TransactionDetailsDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionDetailsDetailsWithDefaults() *TransactionDetailsDetails {
	this := TransactionDetailsDetails{}
	return &this
}

// GetBusinessData returns the BusinessData field value if set, zero value otherwise.
func (o *TransactionDetailsDetails) GetBusinessData() string {
	if o == nil || IsNil(o.BusinessData) {
		var ret string
		return ret
	}
	return *o.BusinessData
}

// GetBusinessDataOk returns a tuple with the BusinessData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionDetailsDetails) GetBusinessDataOk() (*string, bool) {
	if o == nil || IsNil(o.BusinessData) {
		return nil, false
	}
	return o.BusinessData, true
}

// HasBusinessData returns a boolean if a field has been set.
func (o *TransactionDetailsDetails) HasBusinessData() bool {
	if o != nil && !IsNil(o.BusinessData) {
		return true
	}

	return false
}

// SetBusinessData gets a reference to the given string and assigns it to the BusinessData field.
func (o *TransactionDetailsDetails) SetBusinessData(v string) {
	o.BusinessData = &v
}

// GetMultiSignature returns the MultiSignature field value if set, zero value otherwise.
func (o *TransactionDetailsDetails) GetMultiSignature() bool {
	if o == nil || IsNil(o.MultiSignature) {
		var ret bool
		return ret
	}
	return *o.MultiSignature
}

// GetMultiSignatureOk returns a tuple with the MultiSignature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionDetailsDetails) GetMultiSignatureOk() (*bool, bool) {
	if o == nil || IsNil(o.MultiSignature) {
		return nil, false
	}
	return o.MultiSignature, true
}

// HasMultiSignature returns a boolean if a field has been set.
func (o *TransactionDetailsDetails) HasMultiSignature() bool {
	if o != nil && !IsNil(o.MultiSignature) {
		return true
	}

	return false
}

// SetMultiSignature gets a reference to the given bool and assigns it to the MultiSignature field.
func (o *TransactionDetailsDetails) SetMultiSignature(v bool) {
	o.MultiSignature = &v
}

func (o TransactionDetailsDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransactionDetailsDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BusinessData) {
		toSerialize["businessData"] = o.BusinessData
	}
	if !IsNil(o.MultiSignature) {
		toSerialize["multiSignature"] = o.MultiSignature
	}
	return toSerialize, nil
}

type NullableTransactionDetailsDetails struct {
	value *TransactionDetailsDetails
	isSet bool
}

func (v NullableTransactionDetailsDetails) Get() *TransactionDetailsDetails {
	return v.value
}

func (v *NullableTransactionDetailsDetails) Set(val *TransactionDetailsDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionDetailsDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionDetailsDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionDetailsDetails(val *TransactionDetailsDetails) *NullableTransactionDetailsDetails {
	return &NullableTransactionDetailsDetails{value: val, isSet: true}
}

func (v NullableTransactionDetailsDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionDetailsDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


