/*
API Off-Chain del Banco Central

API para exponer datos complementarios de la blockchain a sistemas internos y externos de forma estandarizada.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PriceReference type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PriceReference{}

// PriceReference struct for PriceReference
type PriceReference struct {
	Asset *string `json:"asset,omitempty"`
	Price *float32 `json:"price,omitempty"`
}

// NewPriceReference instantiates a new PriceReference object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPriceReference() *PriceReference {
	this := PriceReference{}
	return &this
}

// NewPriceReferenceWithDefaults instantiates a new PriceReference object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPriceReferenceWithDefaults() *PriceReference {
	this := PriceReference{}
	return &this
}

// GetAsset returns the Asset field value if set, zero value otherwise.
func (o *PriceReference) GetAsset() string {
	if o == nil || IsNil(o.Asset) {
		var ret string
		return ret
	}
	return *o.Asset
}

// GetAssetOk returns a tuple with the Asset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PriceReference) GetAssetOk() (*string, bool) {
	if o == nil || IsNil(o.Asset) {
		return nil, false
	}
	return o.Asset, true
}

// HasAsset returns a boolean if a field has been set.
func (o *PriceReference) HasAsset() bool {
	if o != nil && !IsNil(o.Asset) {
		return true
	}

	return false
}

// SetAsset gets a reference to the given string and assigns it to the Asset field.
func (o *PriceReference) SetAsset(v string) {
	o.Asset = &v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *PriceReference) GetPrice() float32 {
	if o == nil || IsNil(o.Price) {
		var ret float32
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PriceReference) GetPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.Price) {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *PriceReference) HasPrice() bool {
	if o != nil && !IsNil(o.Price) {
		return true
	}

	return false
}

// SetPrice gets a reference to the given float32 and assigns it to the Price field.
func (o *PriceReference) SetPrice(v float32) {
	o.Price = &v
}

func (o PriceReference) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PriceReference) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Asset) {
		toSerialize["asset"] = o.Asset
	}
	if !IsNil(o.Price) {
		toSerialize["price"] = o.Price
	}
	return toSerialize, nil
}

type NullablePriceReference struct {
	value *PriceReference
	isSet bool
}

func (v NullablePriceReference) Get() *PriceReference {
	return v.value
}

func (v *NullablePriceReference) Set(val *PriceReference) {
	v.value = val
	v.isSet = true
}

func (v NullablePriceReference) IsSet() bool {
	return v.isSet
}

func (v *NullablePriceReference) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePriceReference(val *PriceReference) *NullablePriceReference {
	return &NullablePriceReference{value: val, isSet: true}
}

func (v NullablePriceReference) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePriceReference) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


