/*
API Off-Chain del Banco Central

API para exponer datos complementarios de la blockchain a sistemas internos y externos de forma estandarizada.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ContractMetadataParametersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContractMetadataParametersInner{}

// ContractMetadataParametersInner struct for ContractMetadataParametersInner
type ContractMetadataParametersInner struct {
	Name *string `json:"name,omitempty"`
	Type *string `json:"type,omitempty"`
	Value *string `json:"value,omitempty"`
}

// NewContractMetadataParametersInner instantiates a new ContractMetadataParametersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContractMetadataParametersInner() *ContractMetadataParametersInner {
	this := ContractMetadataParametersInner{}
	return &this
}

// NewContractMetadataParametersInnerWithDefaults instantiates a new ContractMetadataParametersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContractMetadataParametersInnerWithDefaults() *ContractMetadataParametersInner {
	this := ContractMetadataParametersInner{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ContractMetadataParametersInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContractMetadataParametersInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ContractMetadataParametersInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ContractMetadataParametersInner) SetName(v string) {
	o.Name = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ContractMetadataParametersInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContractMetadataParametersInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ContractMetadataParametersInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ContractMetadataParametersInner) SetType(v string) {
	o.Type = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ContractMetadataParametersInner) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContractMetadataParametersInner) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ContractMetadataParametersInner) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *ContractMetadataParametersInner) SetValue(v string) {
	o.Value = &v
}

func (o ContractMetadataParametersInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContractMetadataParametersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableContractMetadataParametersInner struct {
	value *ContractMetadataParametersInner
	isSet bool
}

func (v NullableContractMetadataParametersInner) Get() *ContractMetadataParametersInner {
	return v.value
}

func (v *NullableContractMetadataParametersInner) Set(val *ContractMetadataParametersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableContractMetadataParametersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableContractMetadataParametersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContractMetadataParametersInner(val *ContractMetadataParametersInner) *NullableContractMetadataParametersInner {
	return &NullableContractMetadataParametersInner{value: val, isSet: true}
}

func (v NullableContractMetadataParametersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContractMetadataParametersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


