/*
API Off-Chain del Banco Central

API para exponer datos complementarios de la blockchain a sistemas internos y externos de forma estandarizada.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TransactionDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransactionDetails{}

// TransactionDetails struct for TransactionDetails
type TransactionDetails struct {
	TxHash *string `json:"txHash,omitempty"`
	Details *TransactionDetailsDetails `json:"details,omitempty"`
}

// NewTransactionDetails instantiates a new TransactionDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionDetails() *TransactionDetails {
	this := TransactionDetails{}
	return &this
}

// NewTransactionDetailsWithDefaults instantiates a new TransactionDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionDetailsWithDefaults() *TransactionDetails {
	this := TransactionDetails{}
	return &this
}

// GetTxHash returns the TxHash field value if set, zero value otherwise.
func (o *TransactionDetails) GetTxHash() string {
	if o == nil || IsNil(o.TxHash) {
		var ret string
		return ret
	}
	return *o.TxHash
}

// GetTxHashOk returns a tuple with the TxHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionDetails) GetTxHashOk() (*string, bool) {
	if o == nil || IsNil(o.TxHash) {
		return nil, false
	}
	return o.TxHash, true
}

// HasTxHash returns a boolean if a field has been set.
func (o *TransactionDetails) HasTxHash() bool {
	if o != nil && !IsNil(o.TxHash) {
		return true
	}

	return false
}

// SetTxHash gets a reference to the given string and assigns it to the TxHash field.
func (o *TransactionDetails) SetTxHash(v string) {
	o.TxHash = &v
}

// GetDetails returns the Details field value if set, zero value otherwise.
func (o *TransactionDetails) GetDetails() TransactionDetailsDetails {
	if o == nil || IsNil(o.Details) {
		var ret TransactionDetailsDetails
		return ret
	}
	return *o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionDetails) GetDetailsOk() (*TransactionDetailsDetails, bool) {
	if o == nil || IsNil(o.Details) {
		return nil, false
	}
	return o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *TransactionDetails) HasDetails() bool {
	if o != nil && !IsNil(o.Details) {
		return true
	}

	return false
}

// SetDetails gets a reference to the given TransactionDetailsDetails and assigns it to the Details field.
func (o *TransactionDetails) SetDetails(v TransactionDetailsDetails) {
	o.Details = &v
}

func (o TransactionDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransactionDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TxHash) {
		toSerialize["txHash"] = o.TxHash
	}
	if !IsNil(o.Details) {
		toSerialize["details"] = o.Details
	}
	return toSerialize, nil
}

type NullableTransactionDetails struct {
	value *TransactionDetails
	isSet bool
}

func (v NullableTransactionDetails) Get() *TransactionDetails {
	return v.value
}

func (v *NullableTransactionDetails) Set(val *TransactionDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionDetails(val *TransactionDetails) *NullableTransactionDetails {
	return &NullableTransactionDetails{value: val, isSet: true}
}

func (v NullableTransactionDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


