server {
    listen 80;

    root /usr/share/nginx/html;

    # Frontend (React SPA)
    location /ui/ {
        try_files $uri $uri/ /ui/index.html;
    }

    # Redirección opcional raíz → /ui/
    location = / {
        return 302 /ui/;
    }
}