FROM python:alpine3.23

# Instalar dependencias
RUN apk add --no-cache \
    curl \
    jq \
    aws-cli \
    ca-certificates

# Descargar Vault binary
ARG VAULT_VERSION=1.17.3
ADD https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip /tmp/vault.zip
RUN unzip /tmp/vault.zip -d /usr/local/bin/ && \
    chmod +x /usr/local/bin/vault && \
    rm /tmp/vault.zip

COPY unseal.sh /unseal.sh
RUN chmod +x /unseal.sh

ENTRYPOINT ["/unseal.sh"]