apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: credentials-azure-external-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: cluster-external-store-vault # Nombre del SecretStore previamente creado
    kind: ClusterSecretStore
  target:
    name: credentials-azure # Nombre del secreto que se creará
  data:
    - secretKey: cloud # Llave dentro del secret a crear con el valor
      remoteRef:
        key: data/cluster-production # Ruta del secreto dentro de vault
        property: cloud # Propiedad del secreto a tomar del baul
