FROM node:18-alpine

WORKDIR /app

# Copiamos solo lo necesario para instalar dependencias
COPY package*.json ./

RUN npm install --production

# Copiamos el resto del código
COPY . .

EXPOSE 3000

CMD ["npm", "start"]
