apiVersion: v1
kind: Secret
metadata:
  name: jfrog-credentials
  namespace: keycloak
type: Opaque
stringData:
  username: "admin"  # Cambiar por el usuario real
  password: "admin"  # Cambiar por la contraseña real