apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: postgres-cloudnative-kc-pool
  namespace: keycloak
spec:
  cluster:
    name: postgres-cloudnative-kc

  instances: 1
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"