apiVersion: v1
kind: Secret
metadata:
  name: pg-secret-keycloak
  namespace: keycloak
type: Opaque
stringData:
  password: "tu_contraseña_aqui"  # Cambiar por la contraseña real
  username: "admin"  # Cambiar por el usuario real
---
apiVersion: v1
kind: Secret
metadata:
  name: pg-superuser-keycloak
  namespace: keycloak
type: Opaque
stringData:
  username: "postgres"  # Cambiar por el superusuario real
  password: "tu_super_contraseña_aqui"  # Cambiar por la contraseña real