apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: mariadb-auth
  namespace: devlake
spec:
  secretStoreRef:
    name: cluster-external-store-vault
    kind: ClusterSecretStore
  target:
    name: mariadb-auth        # Nombre del secreto en Kubernetes
    creationPolicy: Owner
  data:
    - secretKey: mariadb-root-password    # Clave en el Secret de K8s
      remoteRef:
        key: data/cluster-production   # Ruta en Vault (KV v2)
        property: mariadb-root-password # Clave en Vault

    - secretKey: mariadb-password    # Clave en el Secret de K8s
      remoteRef:
        key: data/cluster-production   # Ruta en Vault (KV v2)
        property: mariadb-password # Clave en Vault

    - secretKey: mariadb-database    # Clave en el Secret de K8s
      remoteRef:
        key: data/cluster-production   # Ruta en Vault (KV v2)
        property: mariadb-database # Clave en Vault
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: devlake-mariadb-auth
  namespace: devlake
spec:
  secretStoreRef:
    name: cluster-external-store-vault
    kind: ClusterSecretStore
  target:
    name: devlake-mariadb-auth        # Nombre del secreto en Kubernetes
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_USER    # Clave en el Secret de K8s
      remoteRef:
        key: data/cluster-production   # Ruta en Vault (KV v2)
        property: mysql-user # Clave en Vault

    - secretKey: MYSQL_PASSWORD    # Clave en el Secret de K8s
      remoteRef:
        key: data/cluster-production   # Ruta en Vault (KV v2)
        property: mariadb-password # Clave en Vault

    - secretKey: MYSQL_DATABASE    # Clave en el Secret de K8s
      remoteRef:
        key: data/cluster-production   # Ruta en Vault (KV v2)
        property: mariadb-database # Clave en Vault
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: encryption-secret
  namespace: devlake
  annotations:
    helm.sh/resource-policy: keep
spec:
  secretStoreRef:
    name: cluster-external-store-vault
    kind: ClusterSecretStore
  target:
    name: encryption-secret # Nombre del secreto en Kubernetes
    creationPolicy: Owner
    # metadata:
    #   annotations:
    #     helm.sh/resource-policy: keep
  data:
    - secretKey: ENCRYPTION_SECRET    # Clave en el Secret de K8s
      remoteRef:
        key: data/cluster-production   # Ruta en Vault (KV v2)
        property: encryption-secret-devlake # Clave en Vault
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: devlake-ui-auth
  namespace: devlake
spec:
  secretStoreRef:
    name: cluster-external-store-vault
    kind: ClusterSecretStore
  target:
    name: devlake-ui-auth # Nombre del secreto en Kubernetes
    creationPolicy: Owner
  data:
    - secretKey: ADMIN_USER    # Clave en el Secret de K8s
      remoteRef:
        key: data/cluster-production   # Ruta en Vault (KV v2)
        property: devlake-admin-user # Clave en Vault
    - secretKey: ADMIN_PASS    # Clave en el Secret de K8s
      remoteRef:
        key: data/cluster-production   # Ruta en Vault (KV v2)
        property: devlake-admin-pass # Clave en Vault