apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-b.yaml
  - pg-secret-keycloak-b.yaml
  - pg-cluster-b.yaml
  - pg-pooler-b.yaml
  - operator/keycloak-crds.yaml
  - operator/keycloak-realmimport-crds.yaml
  - operator/kubernetes-b.yaml
  - kc-providers-configmap-b.yaml
  - keycloak-ins-b.yaml
  - jfrog-secret-b.yaml
  # - ingress-b.yaml  # Opcional