apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: postgres-cloudnative-kc-pool-b
  namespace: keycloak-b
spec:
  cluster:
    name: postgres-cloudnative-kc-b
  instances: 1
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"