apiVersion: v1
kind: Secret
metadata:
  name: pg-secret-keycloak
  namespace: keycloak-b
type: Opaque
stringData:
  password: "tu_contraseña_keycloak_b"  # Cambiar
  username: "admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: pg-superuser-keycloak
  namespace: keycloak-b
type: Opaque
stringData:
  username: "postgres"
  password: "tu_super_contraseña_keycloak_b"  # Cambiar