---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: hyperledger-bevel
  namespace: flux-system
spec:
  url: https://hyperledger.github.io/bevel-helm
  interval: 10m