apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-unseal-sa
  namespace: vault
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-unseal-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["get", "list", "create"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-unseal-role-binding
subjects:
- kind: ServiceAccount
  name: vault-unseal-sa
  namespace: vault
roleRef:
  kind: ClusterRole
  name: vault-unseal-role
  apiGroup: rbac.authorization.k8s.io