apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./kustoms/reposources-kustomization.yaml
  #- ./kustoms/contour-kustomization.yaml # reemplazado por nginx
  - ./kustoms/nginx-ingress-kustomization.yaml
  - ./kustoms/prometheus-kustomization.yaml
  - ./kustoms/vault-kustomization.yaml
  - ./kustoms/postgresql-kustomization.yaml
