apiVersion: v1
kind: Secret
metadata:
  name: credentials-velero
  namespace: velero
data:
  cloud: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gS1ZRS24wSVE4dUNwdmt4YU04VXYKYXdzX3NlY3JldF9hY2Nlc3Nfa2V5ID0gRVZxTlVUVGpNRXh2ajZyNTdvbjh1NENENGl6TzR0VjlzSVNUbWp6Vw==