---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kustom-vault
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./overlays/dev/infrastructure/vault-besu
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  wait: true