apiVersion: v1
kind: Service
metadata:
  name: vault-unseal-backend
  namespace: vault
  labels:
    app: vault-unseal-backend
spec:
  selector:
    app: vault-unseal-backend
  ports:
  - name: backend
    port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP