apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-unseal-data
  namespace: vault
  labels:
    app: vault-unseal-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  # Aumentado a 2Gi para margen
  storageClassName: local-path