apiVersion: v1
kind: Secret
metadata:
  name: credentials-velero
  namespace: velero
type: Opaque
data:
  # Reemplazar con los valores reales en base64, ejecutar:
  # echo -n "[default]
  # aws_access_key_id=AKIAQ2++++++(AccessKeyId)
  # aws_secret_access_key=pry6*********************a1iJc(SecretAccessKey)" | base64 -w 0
    cloud: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkPUFLSUFRMlozSU5KMkNCVFI2TlBUCmF3c19zZWNyZXRfYWNjZXNzX2tleT1wcnk2cmcxK3NMeENsSWdYYmlYa3d4cTM2L01JY2Q4TjAvVWExaUpj