---
#helm install validator-1 -f values/proxy-and-vault/validator.yml -n supplychain-bes --set global.proxy.p2p=15011 besu-node
#helm upgrade validator-1 -f values/proxy-and-vault/validator.yml -n supplychain-bes --set global.proxy.p2p=15011 besu-node
global:
  serviceAccountName: vault             #bcentral #vault-auth
  cluster:
    provider: azure                     #bcentral #aws
    cloudNativeServices: false
  vault:
    type: hashicorp
    network: besu
    address: http://vault.vault:8200    #bcentral #http://vault.demo.com:8200
    authPath: bcentral                  #bcentral #supplychain
    secretEngine: secretsv2
    secretPrefix: "data/testnet"        #bcentral #"data/supplychain"
    role: vault-role
  proxy:
    provider: ambassador
    externalUrlSuffix: bcentral-testnet.svc.cluster.local   #bcentral #test.yourdomain.com
                                                      #bcentral ## Use internal addressing for P2P communication
    p2pProvider: internal                             #bcentral


storage:
  enabled: true
  size: "2Gi"
tessera:
  enabled: false
tls:
  enabled: false
node:
  removeKeysOnDelete: false # this will erase keys - so be careful with this on validators
  isBootnode: false    # set this to true if this node is a bootnode
  usesBootnodes: false
  besu:
    envBesuOpts: ""  
    metrics:
      serviceMonitorEnabled: true
    resources:
      cpuLimit: 0.25
      cpuRequest: 0.05
      memLimit: "1G"
      memRequest: "300M"
    p2p:
      discovery: false
image:
  besu:
    repository: hyperledger/besu
    tag: 23.10.2
