from pydantic import BaseModel, Field
from typing import Optional, List # List is not used here, but kept for consistency with your example
from datetime import datetime, timezone

# Let's assume you might want to link back to a User model eventually,
# though it's not strictly necessary for the users_certs models themselves
# from .user_model import User # If you had a User model to link to

# --- UserCert Models ---

class UserCertBase(BaseModel):
    """
    Base model for user certificate data.
    Fields common to creation and reading, but not necessarily updatable in the same way.
    """
    user_id: int = Field(
        ..., # Required
        description="Foreign key referencing the id in the 'users' table."
    )
    kubeconfig_content: Optional[str] = Field(
        default=None,
        description="The content of the Kubeconfig file as a string."
    )
    objs_created: Optional[str] = Field(
        default=None,
        description="A textual representation (e.g., JSON string) of objects created."
    )

class UserCertCreate(UserCertBase):
    """
    Model for creating a new user certificate entry.
    Inherits all fields from UserCertBase.
    'created_at' will be handled by the database default or a default_factory if needed here.
    'id' will be auto-generated by the database.
    """
    # No additional fields specific to creation beyond UserCertBase for this table structure
    pass

class UserCertUpdate(BaseModel): # Using a separate base for update makes all fields optional cleanly
    """
    Model for updating an existing user certificate entry.
    All fields are optional to allow partial updates.
    """
    user_id: Optional[int] = Field(
        default=None,
        description="Foreign key referencing the id in the 'users' table. Generally not updated, but allowed."
    )
    kubeconfig_content: Optional[str] = Field(
        default=None,
        description="The content of the Kubeconfig file as a string. Set to None to clear."
    )
    objs_created: Optional[str] = Field(
        default=None,
        description="A textual representation (e.g., JSON string) of objects created. Set to None to clear."
    )
    # 'created_at' is typically not updated directly.
    # 'id' is the identifier and not part of the update payload data itself.

class UserCert(UserCertBase):
    """
    Represents a full user certificate record as read from the database.
    Includes database-generated fields like id and created_at.
    """
    id: int = Field(description="Primary key, auto-incremented by the database.")
    created_at: datetime = Field(
        # Pydantic will parse the string from SQLite into a datetime object.
        # If creating an instance directly in Python without this value,
        # it would be good to have a default_factory.
        # For data *from* DB, this field will be populated.
        description="Timestamp when the record was created."
    )

    # If you had a User model and wanted to include the user object:
    # user: Optional[User] = None # Assuming you would fetch and populate this

    class Config:
        from_attributes = True # Pydantic V2
        # orm_mode = True # Pydantic V1

        json_schema_extra = {
            "example": {
                "id": 1,
                "user_id": 101,
                "kubeconfig_content": "apiVersion: v1\nclusters:\n- cluster:...",
                "objs_created": '["deployment/myapp", "service/myapp-svc"]',
                "created_at": "2023-10-27T10:30:00Z" # Example ISO format
            }
        }
