apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret.yaml
# Despliegue mariadb  
  - ./db/mariadb-service.yaml
  - ./db/mariadb-statefulset.yaml
  - ./db/mariadb-configmap.yaml  
# Despliegue Devlake  
  - ./devlake/helmrepo.yaml   
  - ./devlake/release.yaml
# Despliegue monitoreo
  - ./alerting/alertmanagerconfig_devlake.yaml