apiVersion: batch/v1
kind: Job
metadata:
  name: vault-unseal-job
  namespace: vault
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      serviceAccountName: vault-unseal-sa
      containers:
      - name: unseal-script
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          # Esperar a que Vault esté listo
          echo "Esperando a que los pods de Vault estén disponibles..."
          sleep 30
          
          # Ejecutar el script de desbloqueo
          /scripts/unseal.sh
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
        env:
        - name: VAULT_NAMESPACE
          value: "vault"
        - name: CONTAINER_NAME
          value: "vault"
        - name: SECRET_NAME
          value: "vault-unseal-keys"
      volumes:
      - name: script-volume
        configMap:
          name: vault-unseal-script
          defaultMode: 0755
      restartPolicy: Never