apiVersion: v1
kind: Secret
metadata:
  name: vault-unseal-keys
  namespace: vault
type: Opaque
data:
  # Valores en base64 (ya codificados)
  unseal-key-1: ZitUR21abm0wVU9mNm1RbWJnNXpHbCtmZUpmZE5uZm83cGhac0ZCUXgzVWU=
  unseal-key-2: RWtJZDRhWkFyQVZxLzY1NjVxRlFVT3IzcjFDMXhaaVVQb0czcDhRdzI5N2Y=