apiVersion: v1
kind: Secret
metadata:
  name: vault-unseal-keys
  namespace: vault
type: Opaque
data:
  # Valores en base64 (ya codificados)
  unseal-key-1: REZBZDRtREdYN3VjSytjb0JubjFWcml2WVJtUlIrbTh5THRhWndsdnN2UzE=
  unseal-key-2: K3o5Y1MwNFJvR3RhWUc4RDZtSExFbzR3NkpBU2pZMkxyeWRoZHRoUldGczc=
  unseal-key-3: QnQ1Mzd2RSsyN0xZM1BadEpJZFRMcHVIc2tSclNKQU1pQ2RjVXJ3czBvZmg=   