apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault

resources:
  - namespace.yaml
  - secrets-add.yaml
  - vault-repo.yaml
  - vault-release-operator.yaml
  #- ingress.yaml

  - pg-cluster.yaml
  - pg-pooler.yaml
  - cloudnative-initdb-configmap.yaml
  ###- vault-release.yaml ## INSTALL from /tools/vault/01-create-secrets-and-install.sh
  - vault-release-add.yaml