apiVersion: v1
kind: Secret
metadata:
  name: smtp-secrets
  namespace: rbac-manager
type: Opaque
data:
  SMTP_USER: QUtJQTQ3Q1JWWEhCM09DUTdOS1Q=  # base64 encoded
  SMTP_PASSWORD: QkhlbzBKOWJxTGRvUlVsMFpCbXowamV0RGVVYWZqVXlrYnlIc0dLQmpSMHE=  # base64 encoded