# Dockerfile (en la raíz del proyecto)
FROM python:alpine3.23

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

ARG APP_USER=appuser
ARG APP_UID=1000
ARG APP_GID=1000

# Crear usuario y grupo
RUN addgroup -g ${APP_GID} ${APP_USER} \
    && adduser -u ${APP_UID} -G ${APP_USER} -D ${APP_USER}

# Instalar dependencias del sistema
RUN apk update \
    && apk add --no-cache \
        curl \
        ca-certificates \
        sqlite \
        openssl \
        bash \
        gcc \
        musl-dev \
        python3-dev \
        linux-headers \
        libffi-dev \
    && update-ca-certificates \
    && curl -LO https://dl.k8s.io/release/v1.32.0/bin/linux/amd64/kubectl \
    && chmod +x kubectl \
    && mv kubectl /usr/local/bin/kubectl \
    && apk cache clean

WORKDIR /opt/unseal-app

# Copiar requirements.txt (ruta relativa desde el contexto)
COPY requirements.txt /opt/unseal-app/backend/requirements.txt

# Instalar dependencias
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r /opt/unseal-app/backend/requirements.txt

# Copiar el resto del código
COPY . /opt/unseal-app/backend/

# Hacer ejecutables los scripts
RUN chmod +x /opt/unseal-app/backend/bin/*.sh


# Crear directorio de datos para SQLite
RUN mkdir -p /opt/unseal-app/data \
    && chown -R ${APP_USER}:${APP_USER} /opt/unseal-app

USER ${APP_USER}
ENTRYPOINT ["/opt/unseal-app/backend/bin/entrypoint.sh"]

EXPOSE 8000

# Comando de inicio
CMD ["python", "-m", "uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]